### ISSUE TITLE
Proposal: BATLedgerContext

### ISSUE THREAD

**Issue by zenparsing** [brave/rewards#9]
**Scope:** BAT Native Ledger

[Prototype Implementation](https://github.com/brave/brave-core/compare/ksmith-ledger-context#diff-ec105647b6e16952f18e97289ae71299b42e29fa561e351d3d4e120e51c21e2e)

## Problem Statement

Generally, all components within `bat-native-ledger` maintain a raw `LedgerImpl` pointer and assume that the `LedgerImpl` instance will outlive the component. Although code has been organized into separate files, the system is effectively structured as a single massive component. This leads to the following problems:

- Components within `bat-native-ledger` are generally not testable without mocking out the entire system.
- Pervasive mocking leads to hard-to-understand and brittle tests.
- Memory safety is implicit and based on assumptions about the system as a whole. In turn, this makes the system as a whole structurally inflexible.
- Prevalence of "plumbing" code. Introducing new code generally requires changes to many different parts of the codebase. 

## Proposed Solution

A `BATLedgerContext` replaces `LedgerImpl` as the primary coordination point for components. The context object owns the components that are associated with it, and components can access the context in which they live. Components that exist as singletons with a context can register themselves globally.

Example of a singleton component:

```cpp
class MyComponent : public BATLedgerContext::Component {
 public:
  // kComponentKey is required for singleton registration
  static const BATLedgerContext::ComponentKey kComponentKey;

  // Required constructor - called by BATLedgerContext
  explicit MyComponent(BATLedgerContext* context) : Component(context) {}

  void Foo();
};
```

```cpp
const BATLedgerContext::ComponentKey MyComponent::kComponentKey;

void MyComponent::Foo() {
  // Singleton components can be accessed via Get<T>
  auto* other_component = context()->Get<OtherComponent>();

  // Components support weak pointers
  auto weak_ptr = base::AsWeakPtr(this);
}
```

### Comparison

- Components can be tested by providing test implementations of their dependencies, rather than a mock of the entire codebase.
- Memory safety is explicit. The context is guaranteed to outlive components, and components have built-in support for weak pointers.
- No plumbing code is required. Components can simply `#include` the other components that they depend on.

### Backward compatibility

In order to allow interoperability with existing code, a `GetLedgerImpl()` method is provided on `BATLedgerContext`.

### Forward compatibility

In order to help existing code use new features, `LedgerImpl` is provided with a `context()` accessor which allows accessing the current `BATLedgerContext`.

**Comment by bsclifton** [comment]
I took a few minutes to read through and understand the prototype - this is beautiful. I think having a few examples of Tasks (here, not necessarily in the prototype) would help me understand more (and how those get created; ex: by the component). For example, how would creating a wallet break into tasks?

I love the power this gives devs for testing:
1. Services can easily be swapped out for a mock implementation. Those mock implementations can just no-op versus creating tasks (when you're not worried about testing the task side of things)
1. Providing interface for Tasks to be mocked should allow us to provide fake task implementations and verify the call order of those tasks (sequential, etc) by the real implementation.
1. Individual tasks should be easier to test

**Comment by zenparsing** [comment]
@bsclifton Great questions! I have another abstraction in mind for tasks. As you saw in the prototype, there's a `StartTask<T>` method on the context - this creates a task component, owned by the context, which is deleted when the task completes.

I'd like to create a helper class that makes defining tasks really easy. For example, a simple task to get unspent tokens from the database might look like:

```cpp
class GetAvailableTokensTask : public BATLedgerTask<std::list<std::string>> {
 public:
  void Start() {
    std::string sql = R"sql(
      select token_value from unblinded_tokens where redeemed_at = 0
    )sql";

    // Use SQLStore to execute a query:
    context()->Get<SQLStore>()->Query(sql).Listen(
        base::BindOnce(&GetAvailableTokensTask::QueryCompleted, base::AsWeakPtr(this)));
  }

  void QueryCompleted(const mojom::DBCommandResponsePtr& response) {
    std::list<std::string> tokens;
    for (SQLReader reader(response); reader.Step();) {
      tokens.push_back(reader.ColumnString(0));
    }
    Complete(std::move(tokens));
  }
};
```

Used like this:

```cpp
auto result = context()->StartTask<GetAvailableTokensTask>();
result.Listen(...);
```

See https://github.com/brave/rewards/issues/10 for where the `Listen(...)` thing comes from.

**Comment by bridiver** [comment]
So, sorry to be finding this late, but this seems to be creating a parallel system to KeyedServices and that doesn't seem like a good idea to me because it further complicates understanding the code vs the rest of the codebase. Most commonly KeyedServices are BrowserContextKeyedServices, but that is by no means necessary. They can be keyed by whatever class you want and swapping out implementations is done through factories just like in `RewardsServiceFactory::SetServiceForTesting`

**Comment by bridiver** [comment]
also see `SupportsUserData`

**Comment by bridiver** [comment]
in addition, KeyedServices provide a mechanism to ensure that their dependencies are created and destroyed in the correct order so you don't end up with inter-service issues

**Comment by bridiver** [comment]
and also `components/keyed_service/core/dependency_manager` for managing dependencies and creating services in factories. Some examples are `components/keyed_service/ios/browser_state_dependency_manager` and `components/keyed_service/content/browser_context_dependency_manager`

**Comment by zenparsing** [comment]
Thanks for taking a look - the more eyes the better!

Yes, I'm aware of (but by no means an expert in) `BrowserContext` and `KeyedService`, and the overall idea was an inspiration. IIUC, each "service" instance requires both a `KeyedService` and an associated factory singleton, correct? If so, I don't think that's what we want, since the intent is that there would perhaps be dozens of these components. Having to create a factory for everything would be overkill. At least, it wouldn't fulfill the goal of making `bat-native-ledger` code easier to understand and code against.

Using `SupportsUserData` is an interesting idea, in that it allows you to store a random thing in a map keyed by another random thing, but isn't that just the map in `BATLedgerContext`? If the suggestion is to use `SupportsUserData` instead of the map, then what is the advantage? If the suggestion is to use `SupportsUserData` instead of `BATLedgerContext`, the it doesn't meet the ergonomics goal of making the code easier to write.

I do like how `SupportsUserData` has a sequence check though.

**Comment by bridiver** [comment]
I don’t think having a factory is “overkill”. It’s one small class to implement. Also the dependency manager ensures that everything starts up and shuts down in the correct order when there are inter component dependencies. The main thing here is that we want to follow established patterns in chromium so we have consistency in the code. I also don’t want to further confuse the term “component” which already has several meaning in different places. The primary goal IMO shouldn’t be making the code easier to write, it should be making the code easier to understand. The abstractions and frameworks in chromium have stood the test of time and adding something new is just another thing someone has to learn when looking at the ledger code. We want more consistency across the codebase and having a one-off framework for ledger really does not seem like a good idea to me even it has some advantages over the existing framework.
